### ISSUE TITLE
Colored background on lists styling

### ISSUE THREAD

**Issue by thatstheway** [glutanimate/popup-dictionary#13]
## Prerequisite checklist

* [X ] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [X ] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [x] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

(Screenshot attached)

I have my ordered and unordered lists stylized (CSS below) with a dark background color and white text. Unfortunately, when Popup Dictionary pulls those cards up, the background remains dark but the text is changed to black and so becomes very difficult to read. It would be great if Popup-dictionary. just forced everything to be black text on a white background, including lists.

CSS:
ul li {
  background: 	#3D4755;
  width: 98%;
  text-align: left;
  margin: 2px;
  border-radius: 5px;
  padding-left: 7px;
}

ol li {
  background: 	#3D4755;
  width: 98%;
  text-align: left;
  margin: 2px;
  border-radius: 5px;
  padding-left: 7px;
}

<img width="1920" alt="Screen Shot 2019-04-20 at 3 54 08 PM" src="https://user-images.githubusercontent.com/37633100/56461714-58047c80-6385-11e9-8f38-a3f5b97c6186.png">

## Version information

**Anki**

Version 2.1.11 (3cf770c7)
Qt 5.12.1 PyQt 5.11.3

**System**

- Operating system: [macOS]
- Version: [10.14.4]

**Comment by glutanimate** [comment]
Hi @thatstheway,

Thanks for the detailed report!

Pop-up Dictionary ignores template CSS, so any type of formatting you see in the pop-ups is actually produced by the note content itself rather than secondary modifications. That means that those lists actually look like that due to inline HTML styling. Things like that can sometimes be inadvertently introduced to notes when copy/pasting stuff.

Unfortunately this also means that there is no automatic way for Pop-up Dictionary to override these styles, as it can't know which ones are desirable and which ones aren't (i.e. I can't blanket-remove inline styles as that would also get rid of useful stuff like colored text, etc.).

So to properly address this, the right approach would be to introduce support for a custom stylesheet wherein users could customize the styling of the pop-up, including overriding undesirable inline styles.

Please feel free to track the progress of that here: https://github.com/glutanimate/popup-dictionary/issues/14
