### ISSUE TITLE
Support for MathJax

### ISSUE THREAD

**Issue by sahrawat** [glutanimate/popup-dictionary#55]
MathJax is breaking on my system, see image below:

![image](https://user-images.githubusercontent.com/16423990/95608792-4cc27680-0a7b-11eb-84c2-b91cc5367d38.png)

The config is the default except `dictionaryDefinitionFieldName` which is now `edit:Back` but it doesn't behave correctly with the defaults anyway.

I tried messing around and adding MathJax from CDN directly into `template.py`'s var `card_back` but to no avail. Is there any workaround till this gets fixed? Or maybe I am missing something?

Just to be clear, it behaves exactly the way it is supposed to when reviewing the card:
![image](https://user-images.githubusercontent.com/16423990/95611863-0c192c00-0a80-11eb-9933-73170f66efca.png)

**Comment by codes-lukas** [comment]
I am sorry for the "me too" comment, but I need this add-on so bad.
MathJax is not working for me either and I only use Anki for mathematics.

I am not involved in the programming of Anki (-add-ons), so I hope somebody can provide an understandable workaround.

**Comment by codes-lukas** [comment]
The problem here is that the search results get dynamically added to the web view (HTML) **AFTER** MathJax has already been called. So you need to recall MathJax in order to process the newly added MathJax strings.

Here is a quick, dirty fix that I hope everybody reading this will understand:

1. Install the add-on
2. Go to the menu `Tools` -> `Add-ons`
3. Click on the add-on and hit `View Files`
4. Open the file `menu.py`
5. Change line 73, where the variable `html_reslist` gets defined, to this: `html_reslist = """<div class="tt-reslist">{}</div><script>MathJax.Hub.Queue(["Typeset",MathJax.Hub]);</script>"""`
6. Save the file
7. Restart Anki

**Comment by codes-lukas** [comment]
Shouldn't this issue stay open, so it's more visible and someone may make a pull request, someday?
